version: '3'

services:
  cassandra1:
    image: cassandra:4.1
    container_name: cassandra1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_DC=datacenter1
    volumes:
      - cassandra1_data:/var/lib/cassandra

  cassandra2:
    image: cassandra:4.1
    container_name: cassandra2
    ports:
      - "9043:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_DC=datacenter1
    volumes:
      - cassandra2_data:/var/lib/cassandra
    depends_on:
      - cassandra1

  cassandra3:
    image: cassandra:4.1
    container_name: cassandra3
    ports:
      - "9044:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_DC=datacenter1
    volumes:
      - cassandra3_data:/var/lib/cassandra
    depends_on:
      - cassandra1
      - cassandra2

volumes:
  cassandra1_data:
  cassandra2_data:
  cassandra3_data: 